### PR TITLE
Rewrite ofxparse to take advantage of more robust extension of BeautifulSoup

### PR DESCRIPTION
**Pull request by rdsteed**
I ran across ofxparse while working on my own program (also using Beautifulsoup) to handle my various OFX/QFX files from banks, credit cards and investments.   I had already extended BeautifulSoup4's "builder" for html.parser to work directly with my OFX/QFX files.

As I was looking at ofxparse, I noted that much of the code was devoted to preprocessing OFX files for BeautifulSoup by skipping untagged headers, adding explicit closing tags for the optional closing tags allowed by OFX v1, and handling character set encoding/decoding issues.  I realized that my extension to BeautifulSoup4 meant that these issues could now be handled by BeautifulSoup itself.  Letting BeautifulSoup do all this "heavy lifting" could simplify ofxparse and make it more robust.

My new classes and associated methods for handling OFX are placed in a module name OFXSoup that only depends on BeautifulSoup4.

Refactoring ofxparse:

Since there is no longer a missing closing tag issue in BeautifulSoup's parsing, it was possible to eliminate all file handling, file preprocessing and encoding/decoding from ofxparse and generally simplify code.

Classes and functions eliminated:
def skip_headers(fh):
def try_decode(string, encoding):
def is_iterable(candidate):
def save_pos(fh):
class OfxFile(object):
class OfxPreprocessedFile(OfxFile):		

function added:
def headers(soup): (headers previously handled in OFXFile class and preprocessing)

function rewritten:
def soup_maker(fh): (import from OFXsoup and use OFXParserTreeBuilder() in BeautifulSoup call)

class method rewritten in class OfxParser(object):
def parse(cls_, file_handle, fail_fast=True):
- eliminate OfxPreProcessedFile object
- call soup_maker without preprocessing or positioning OFX file handle
- call headers() after making soup

test_parse.py (unit tests) rewritten: 
- Eliminated all tests for the (removed) OfxPreprocessedFile and OfxFile classes.
- New tests were added that assert proper generation of headers for all of the existing test files.
- Method testThatReturnedAccountAlsoHasAStatement was changed to use stmtrs.find_all instead of stmtrs.find (see issue #95).

Pros:
1. Moves all file handling, optional closing tag handling, and character set encoding/decoding to BeautifulSoup.
2. Handles all v1 and v2 OFX files with or without optional closing tags
3. Fixes many of the remaining open issues
4. Uses built in html.parser (no need for lxml module or associated compiled binaries).

Cons:
1. Fairly radical refactoring.  Though it passes all unit tests, there may be unanticipated side effects.
2. Only tested in Python versions 2.7 and 3.5.
3. Have not assured PEP8 styling

Updates to this pull request:
3/27/2016 - Now running in python 3.5.  Had to change deprecated <> to !=.  Also, fixed an assertion to compare ordered dictionaries in TestHeader().
3/30/2016 - Rewrote this description to better explain what was done and why.

### CODE REVIEW

**Comment by rdsteed** [comment]
Never mind.

**Comment by jseutter** [comment]
Why did you close this PR?

**Comment by rdsteed** [comment]
It has been a couple months, but there a couple of reasons that I recall.

1.  I began to doubt the wisdom of making unofficial additions to BS4's builders.  Although BS4 clearly is designed to support pluggable parser tree "builders", I became concerned that it was not appropriate to make ofxparse dependent on my personal fork of BS4.

2.  Between the time that I submitted the pull request and closing it, I perceived that ofxparse had become committed to the lxml parser rather than the htmlparser I used in my BS4 OFXParserTreeBuilder.

All in all, I think I was concerned that what I was submitting was just too radical a change in approach.

If there is interest in pursuing this approach, let me know, and I can reopen.

**Comment by rdsteed** [comment]
I've posted an explanation comment in the pull request.

Dennis

**Comment by jseutter** [comment]
Ah.  Thanks for enlightening me :).  I'm not strongly tied to one library over another, and I honestly couldn't tell you that either lxml or BS4 is better.  Since lxml seems to be working for most people so far I am content to stick with that.  About the only thing I would see as an improvement is removing an external dependency.

Thank you for taking the time to consider ofxparse in your coding.  I know it takes courage to abandon your code.

**Pull request closed without merging**
