### PR TITLE
Support for 'transfers' and 'inv401ksource' in Investment files

### PR DESCRIPTION
**Pull request by nathangrigg**
My 401k files have a couple of tags that aren't recognized that I would like parsed.

1. A transfer transaction. This is how vanguard records annual fees.
2. Inv401ksource, which distinguishes employee contributions from employer match.

### CODE REVIEW

**Comment by nathangrigg** [comment]
Friendly ping

This is a useful project, but you perhaps are busy on other things. Would you like any help?

**Comment by jseutter** [comment]
Thanks for your fix!  I know it has been a long time, are you still interested in helping?

**Comment by nathangrigg** [comment]
Yes, I would be happy to.

**Comment by jseutter** [comment]
I added you as a collaborator on ofxparse.  The biggest things I need help with are responding to drive-by PR's in a timely manner (I'm terrible at this) and working through the backlog of PRs.  If you can help out with either of those, I can keep making releases.

My basic check when merging in a PR is to look at the code changes for any glaring issues and check if the test suite still passes.  If it does, then I merge it in.

**Comment by nathangrigg** [comment]
Sounds good.

**Pull request merged**
