### PR TITLE
Added option transaction types and related fields

### PR DESCRIPTION
**Pull request by nall**
For my purposes I need option transaction types and a few related fields. This diff adds them.

### CODE REVIEW

**Comment by jseutter** [comment]
Hey, the InvestmentTransaction class has been refactored to be more flexible with transaction types.  If this is still pertinent to you, could you test with an updated master and see if it can parse your .ofx files?

**Comment by nall** [comment]
Thanks, yes it's still pertinent. Does your new master include support for the option types and fields from my original pull request or should I attempt to merge my changes in?

**Comment by jseutter** [comment]
Yes, it should handle option types.  Someone submitted a change that makes InvestementTransaction.type just be the lowercase of the name, so theoretically it should handle just about anything.  I don't have an example file to test with, so YMMV. :)

Cheers!

**Comment by nall** [comment]
Sorry to reopen this, but it looks like the shares_per_contract support in my patch wasn't part of the change that made it in.

If I create another patch with just that support, will you accept it?

**Pull request closed without merging**
