### PR TITLE
Handle POSOTHER and MKTVAL in investment statements

### PR DESCRIPTION
**Pull request by jantman**
I'm using this to pull down investment statements from TIAA-CREF, and found a few fields that weren't being parsed; specifically, positions of type POSOTHER, and the MKTVAL (Market Value) field in positions.

I've added support for both of those and unit tests for them (both using an anonymized version of a TIAA-CREF statement for POSOTHER, and by addking the MKTVAL support to positions in existing fixtures).

Thank you SOOOO much for this library!

### CODE REVIEW

**Comment by jseutter** [comment]
You rock, jantman.  We are hugely encouraged when people find this library useful and take the time to tell us. :)

**Comment by jantman** [comment]
Thanks! It certainly was a great find. I'm using it in my [biweeklybudget](https://github.com/jantman/biweeklybudget) project, which is really rough and definitely not "end user" software, but is intended to be workable personal finance and budgeting software for people who are paid biweekly (i.e. every 14 days, or every other X-day), since nothing else out there seems to do that...

**Comment by jantman** [comment]
@jseutter Thank you so much for merging this. Are there any plans to get a new release up on PyPI any time soon?

**Comment by jseutter** [comment]
Hi Jason, I'm in the middle of real life stuff and plan to have a release out afterwards. If I don't have a release out by mid-July please ping me.

**Comment by jantman** [comment]
@jseutter Ok, no worries, I completely understand that and was in a similar position myself a few months ago. Thanks for taking the time to update. No rush.

**Pull request merged**
