### PR TITLE
Parse all aggregations

### PR DESCRIPTION
**Pull request by egh**
I was missing transactions when using ledger-autosync. It turns out they were `<TRANSFER>` aggregations. This modifies ofxparse to parse all aggregation types (as defined in 2.1.1 of the spec (http://www.ofx.net/DownloadPage/Downloads.aspx)). It also changes the `type` attribute of the `InvestmentTransaction` to be a string instead of the less useful number.

Thanks!

### CODE REVIEW

**Comment by egh** [comment]
Related: #74 but this a little more comprehensive, and also includes a behavior change. Thank you!

**Comment by egh** [comment]
If you'd prefer, I can switch back to the enum-style type. I notice you are using that pattern elsewhere.

**Comment by jseutter** [comment]
I'm fine with the pattern you used.  Thank you for the fixes (and tests)!

**Comment by jseutter** [comment]
I also added you to AUTHORS

**Comment by egh** [comment]
Thank you!

**Pull request merged**
